apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
- backup.yaml
- ha.yaml
- gotosocial.yaml
- jellyfin.yaml
- qbittorrent.yaml
- photos.yaml
- metatube.yaml
- zhufeng-vm.yaml
- dev-vm.yaml
