apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "infra"
resources: 
# Storage
- "mimir.yaml"
- "loki.yaml"
- "valkey.yaml"
- "postgres.yaml"
- "versitygw.yaml"
# Monitor
- "gotk-monitor.yaml"
- "exporters.yaml"
- "alloy.yaml"
- "grafana.yaml"
# Network
- "traefik.yaml"
- "inadyn.yaml"
