apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources: 
- "storage/pvc.yaml"
- "storage/mimir.yaml"
- "storage/loki.yaml"
- "storage/valkey.yaml"
- "storage/postgres.yaml"
- "storage/versitygw.yaml"

- "monitor/grafana.yaml"
- "monitor/alloy.yaml"
- "monitor/gotk-monitor.yaml"
- "monitor/exporters.yaml"

- "network/cert-manager.yaml"
- "network/traefik.yaml"
- "network/inadyn.yaml"
