apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "infra"
resources: 
- "pv.yaml"
- "updateconfig.yaml"
- "traefik.yaml"
- "inadyn.yaml"
- "loki.yaml"
- "mimir.yaml"
- "exporters.yaml"
- "alloy.yaml"
- "grafana.yaml"
- "nanomq.yaml"
- "valkey.yaml"
- "postgres.yaml"
