apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources: 
- "namespaces.yaml"
- "grafana-helm.yaml"
- "bitnami-helm.yaml"
- "jetstack-helm.yaml"
- "traefik-helm-crds.yaml"
- "prometheus-helm-crds.yaml"
- "https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.crds.yaml"
- "pv.yaml"
- "k0s-updateconfig.yaml"
