apiVersion: "kustomize.config.k8s.io/v1"
kind: "Kustomization"
namespace: "infra"
resources: 
- "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/standard-install.yaml"
- "prometheus.yaml"
