apiVersion: "kustomize.config.k8s.io/v1"
kind: "Kustomization"
resources: 
- "namespaces.yaml"
- "prometheus-helm-crd.yaml"
- "grafana-helm.yaml"
- "bitnami-helm.yaml"
- "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/standard-install.yaml"
- "pv.yaml"
- "k0s-updateconfig.yaml"
