---
apiVersion: "source.toolkit.fluxcd.io/v1"
kind: "HelmRepository"
metadata:
  name: "prometheus-community"
  namespace: "infra"
spec:
  interval: "30m"
  url: "https://prometheus-community.github.io/helm-charts"
---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: "HelmRelease"
metadata:
  name: "prometheus-operator-crds"
  namespace: "infra"
spec:
  interval: "30m"
  chart:
    spec:
      chart: "prometheus-operator-crds"
      sourceRef:
        kind: "HelmRepository"
        namespace: "infra"
        name: "prometheus-community"
  install:
    crds: "CreateReplace"
  upgrade:
    crds: "CreateReplace"
