---
apiVersion: "source.toolkit.fluxcd.io/v1"
kind: "HelmRepository"
metadata:
  name: "traefik"
  namespace: "infra"
spec:
  interval: "24h"
  url: "https://traefik.github.io/charts"
---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: "HelmRelease"
metadata:
  name: "traefik-crds"
  namespace: "infra"
spec:
  interval: "30m"
  chart:
    spec:
      chart: "traefik-crds"
      sourceRef:
        kind: "HelmRepository"
        namespace: "infra"
        name: "traefik"
  install:
    crds: "CreateReplace"
  upgrade:
    crds: "CreateReplace"

