---
apiVersion: "source.toolkit.fluxcd.io/v1"
kind: "HelmRepository"
metadata:
  name: "traefik"
  namespace: "infra"
spec:
  type: "oci"
  interval: "30m"
  url: "oci://ghcr.io/traefik/helm/traefik"
---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: "HelmRelease"
metadata:
  name: "traefik-crd"
  namespace: "infra"
spec:
  interval: "30m"
  chart:
    spec:
      chart: "traefik-crds"
      sourceRef:
        kind: "HelmRepository"
        namespace: "infra"
        name: "traefik"
  install:
    crds: "CreateReplace"
  upgrade:
    crds: "CreateReplace"

